version: "3"
services: 
    app:
        container_name: movie_project
        restart: always
        build: .
        links: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
                - "27018:27017"